In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("churn_modelling.csv")

df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [4]:
df.drop(columns=['RowNumber', 'CustomerId', 'Surname'], inplace=True)

In [5]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [6]:
df.isna().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [7]:
df.describe()

CreditScore           Age        Tenure        Balance  NumOfProducts  \
count  10000.000000  10000.000000  10000.000000   10000.000000   10000.000000   
mean     650.528800     38.921800      5.012800   76485.889288       1.530200   
std       96.653299     10.487806      2.892174   62397.405202       0.581654   
min      350.000000     18.000000      0.000000       0.000000       1.000000   
25%      584.000000     32.000000      3.000000       0.000000       1.000000   
50%      652.000000     37.000000      5.000000   97198.540000       1.000000   
75%      718.000000     44.000000      7.000000  127644.240000       2.000000   
max      850.000000     92.000000     10.000000  250898.090000       4.000000   

         HasCrCard  IsActiveMember  EstimatedSalary        Exited  
count  10000.00000    10000.000000     10000.000000  10000.000000  
mean       0.70550        0.515100    100090.239881      0.203700  
std        0.45584        0.499797     57510.492818      0.402769  
min        0.00000        0.000000        11.580000      0.000000  
25%        0.00000        0.000000     51002.110000      0.000000  
50%        1.00000        1.000000    100193.915000      0.000000  
75%        1.00000        1.000000    149388.247500      0.000000  
max        1.00000        1.000000    199992.480000      1.000000

In [8]:
# categorical to numerical(Geography)
from sklearn.preprocessing import LabelEncoder

geography_encode=LabelEncoder()
df["Geography"]=geography_encode.fit_transform(df["Geography"])

In [9]:
# categorical to numerical(Gender)
gender_encode=LabelEncoder()
df["Gender"]=gender_encode.fit_transform(df["Gender"])

In [14]:
geography_encode.classes_

array(['France', 'Germany', 'Spain'], dtype=object)

In [17]:
gender_encode.classes_

array(['Female', 'Male'], dtype=object)

In [18]:
df.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [19]:
# FS

x = df.drop(columns=["Exited"])
y = df.Exited

In [20]:
# splitting dataset
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [21]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)


In [23]:
# building ANN
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

classifier = Sequential()

In [26]:
# input layer
classifier.add(Dense(activation="relu",input_dim=x_train.shape[1],units=256))

In [27]:
# hidden Layer
classifier.add(Dense(activation = 'relu', units=512))
classifier.add(Dense(activation = 'relu', units=256))
classifier.add(Dense(activation = 'relu', units=128))

In [28]:
# output layer
classifier.add(Dense(activation = 'sigmoid', units=1))

In [29]:
# compile
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# loss/metrics are optional

In [30]:
classifier.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 256)               2816      
                                                                 
 dense_1 (Dense)             (None, 512)               131584    
                                                                 
 dense_2 (Dense)             (None, 256)               131328    
                                                                 
 dense_3 (Dense)             (None, 128)               32896     
                                                                 
 dense_4 (Dense)             (None, 1)                 129       
                                                                 
Total params: 298753 (1.14 MB)
Trainable params: 298753 (1.14 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [31]:
# fit model
classifier.fit(x_train,y_train,epochs=10,batch_size=32)

Epoch 1/10
250/250 [==============================] - 11s 24ms/step - loss: 0.4062 - accuracy: 0.8294
Epoch 2/10
250/250 [==============================] - 4s 15ms/step - loss: 0.3577 - accuracy: 0.8533
Epoch 3/10
250/250 [==============================] - 4s 14ms/step - loss: 0.3449 - accuracy: 0.8586
Epoch 4/10
250/250 [==============================] - 3s 14ms/step - loss: 0.3364 - accuracy: 0.8626
Epoch 5/10
250/250 [==============================] - 3s 12ms/step - loss: 0.3277 - accuracy: 0.8655
Epoch 6/10
250/250 [==============================] - 3s 11ms/step - loss: 0.3246 - accuracy: 0.8674
Epoch 7/10
250/250 [==============================] - 3s 14ms/step - loss: 0.3179 - accuracy: 0.8690
Epoch 8/10
250/250 [==============================] - 3s 14ms/step - loss: 0.3136 - accuracy: 0.8720
Epoch 9/10
250/250 [==============================] - 3s 14ms/step - loss: 0.3104 - accuracy: 0.8721
Epoch 10/10
250/250 [==============================] - 3s 13ms/step - loss: 0.3030 - accur

In [32]:
# gives probability
prediction = classifier.predict(x_test)
prediction


63/63 [==============================] - 1s 12ms/step


array([[0.0094989 ],
       [0.31173775],
       [0.00448108],
       ...,
       [0.22895226],
       [0.02464571],
       [0.3160847 ]], dtype=float32)

In [36]:
prediction = (prediction > 0.5)
prediction

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [39]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

cm = confusion_matrix(y_test,prediction)
cm

array([[1485,   95],
       [ 210,  210]], dtype=int64)

In [40]:
print("Classification Report: \n",classification_report(y_test,prediction))

Classification Report: 
               precision    recall  f1-score   support

           0       0.88      0.94      0.91      1580
           1       0.69      0.50      0.58       420

    accuracy                           0.85      2000
   macro avg       0.78      0.72      0.74      2000
weighted avg       0.84      0.85      0.84      2000



In [41]:
print("Accuracy:\n",accuracy_score(y_test,prediction))

Accuracy:
 0.8475
